### ISSUE TITLE
Uncaught Error: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by Aeromarino** [tidalcycles/atom-tidalcycles#111]
Hello everyone, Tidial Cycles doesn`t run anymore after moving to a new mac with Catalina running. Can anybody help, what does this mean? [Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 3.10.1

### Stack Trace

Uncaught Error: Cannot call write after a stream was destroyed

```
At events.js:171

Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at Ghci.writeLine (/packages/tidalcycles/lib/ghci.js:20:24)
    at REPL.tidalSendLine (/packages/tidalcycles/lib/repl.js:138:15)
    at REPL.tidalSendExpression (/packages/tidalcycles/lib/repl.js:129:10)
    at doIt (/packages/tidalcycles/lib/repl.js:177:12)
    at REPL.evalWithRepl (/packages/tidalcycles/lib/repl.js:181:5)
    at REPL._eval (/packages/tidalcycles/lib/repl.js:154:10)
    at HTMLElement.tidalcyclesEvalMultiLine (/packages/tidalcycles/lib/repl.js:40:49)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349780)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1230988)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1227122)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284829)
```

### Commands

```
  2x -1:36.3.0 tidalcycles:eval-multi-line (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.2.16 
tidalcycles 3.10.1 
```

**Comment by ndr-brt** [comment]
Is this issue reproducible?

**Comment by Aeromarino** [comment]
Yes it was. But anymway I could solve the problem with this:

https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/
