### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by deepbluesome** [tidalcycles/atom-tidalcycles#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 0.8.6

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:160

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:706:26)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at REPL.stdinWrite (/packages/tidalcycles/lib/repl.js:72:25)
    at REPL.tidalSendLine (/packages/tidalcycles/lib/repl.js:76:14)
    at REPL.initTidal (/packages/tidalcycles/lib/repl.js:67:18)
    at REPL.start (/packages/tidalcycles/lib/repl.js:92:14)
    at /packages/tidalcycles/lib/repl.js:21:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.17.0/resources/app/src/atom-environment.js:1286:1)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.17.0/resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:34.6.0 core:save-as (ul.list-inline.tab-bar.inset-panel)
     -0:21 tidalcycles:boot (input.hidden-input)
```

### Non-Core Packages

```
tidalcycles 0.8.6 
```

**Comment by kendfss** [comment]
Hi, how did you solve this issue?
Cheers
