### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by Spaghet** [tidalcycles/atom-tidalcycles#16]
[Enter steps to reproduce:]

1. ... Follow the tidal install directions: https://tidalcycles.org/getting_started.html
2. ... `d1 $ sound "bd sn"

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Windows 10
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 0.8.7

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At C:\Users\rikuo\AppData\Local\atom\app-1.18.0\resources\app\node_modules\text-buffer\lib\range.js:33

TypeError: Cannot read property 'start' of undefined
    at Function.module.exports.Range.fromObject (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/range.js:33:37)
    at TextBuffer.module.exports.TextBuffer.getTextInRange (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:412:42)
    at TextEditor.module.exports.TextEditor.getTextInBufferRange (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:956:32)
    at REPL.getMultiLineExpression (/packages/tidalcycles/lib/repl.js:184:33)
    at REPL.currentExpression (/packages/tidalcycles/lib/repl.js:157:25)
    at REPL._eval (/packages/tidalcycles/lib/repl.js:104:39)
    at /packages/tidalcycles/lib/repl.js:30:55)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:15 command-palette:toggle (input.hidden-input)
     -1:13.4.0 core:confirm (input.hidden-input)
     -1:13.4.0 tree-view:show (input.hidden-input)
     -1:11.3.0 intentions:highlight (input.hidden-input)
     -1:11.2.0 core:save (input.hidden-input)
     -0:55.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.editor-background.theme-solarized-dark-syntax.theme-atom-material-ui)
     -0:53.3.0 command-palette:toggle (input.hidden-input)
     -0:51.1.0 core:move-down (input.hidden-input)
     -0:48.4.0 core:confirm (input.hidden-input)
     -0:48.3.0 tidalcycles:boot (input.hidden-input)
     -0:48.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.editor-background.theme-solarized-dark-syntax.theme-atom-material-ui)
     -0:19.7.0 core:backspace (input.hidden-input)
     -0:14.8.0 intentions:highlight (input.hidden-input)
     -0:14.7.0 core:save (input.hidden-input)
  2x -0:13.7.0 intentions:highlight (input.hidden-input)
     -0:12.6.0 tidalcycles:eval-multi-line (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.0.4 
autocomplete-haskell 0.7.2 
busy-signal 1.4.3 
custom-folds 1.9.4 
editor-background 1.2.38 
editor-stats 0.17.0 
file-icons 2.1.7 
fonts 3.0.2 
haskell-ghc-mod 1.19.9 
highlight-selected 0.13.1 
ide-haskell 1.9.6 
ide-haskell-cabal 1.9.2 
ide-haskell-hasktags 0.0.11 
ide-haskell-repl 0.6.0 
intentions 1.1.2 
japanese-word-selection 0.4.0 
language-haskell 1.12.1 
language-markdown 0.23.0 
linter 2.2.0 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-hlint 1.0.1 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
pigments 0.39.1 
remote-atom 1.3.10 
tidalcycles 0.8.7 
```

C:\Users\rikuo>cabal --version
cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library

C:\Users\rikuo>ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2

SuperCollider version 3.8.0 64bit 
`SuperDirt: listening to Tidal on port 57120`

Not sure what else information you need...

**Comment by Spaghet** [comment]
I think I just pressed shift-enter on a line with no code on it... lol
