### ISSUE TITLE
Failed to activate the tidalcycles package

### ISSUE THREAD

**Issue by freeeco** [tidalcycles/atom-tidalcycles#171]
I'm getting an error if I try to use tidal-listener interpreter (I'm on a  Mac, I installed tidal-listener version 0.1.0.0 using Cabal)

I get this error in atom -->

t> Listening for tidal-listener responses 
tidal-listener: WITH_GHC: getEnv: does not exist (no environment variable)

I tried installing latest GHC, Cabal, using latest Tidal (1.7.8) etc, any ideas? The stack trace is below

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.15.7
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 3.16.14

### Stack Trace

Failed to activate the tidalcycles package

```
At Cannot read property 'browseTidal' of undefined

TypeError: Cannot read property 'browseTidal' of undefined
    at /packages/tidalcycles/lib/autocomplete-provider.js:13:11)
    at Object.autocompleteProvider (/packages/tidalcycles/lib/tidalcycles.js:119:14)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3394001)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3391043)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188366)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:351958)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350801)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:786918)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:794889)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -0:32.1.0 tidalcycles:reboot (input.hidden-input)
  2x -0:06.2.0 core:copy (div.tidalcycles.console.native-key-bindings)
```

### Non-Core Packages

```
ide-haskell 2.7.0 
language-haskell 1.23.0 
minimap 4.40.0 
multi-cursor-increment 0.1.1 
tidalcycles 3.16.14 
```

**Comment by ndr-brt** [comment]
I think that's because, with tidal-listener, the GHC component is not initialized, because tidal-listener should work without GHC.
But, GHC component is used for autocomplete feature. Try to disable autocomplete from the configuration.

**Comment by freeeco** [comment]
I tried disabling autocomplete in the package config but I'm still getting the same error.

**Comment by ndr-brt** [comment]
Released on v3.16.17

**Comment by freeeco** [comment]
I just tried updating to the new v3.16.17 but still getting the same error here on my mac -->

tidal-listener: WITH_GHC: getEnv: does not exist (no environment variable)

**Comment by ndr-brt** [comment]
That's not the same error as the one mentioned in the first command, and that seems like a `tidal-listener` issue.
What if you execute `tidal-listener` from a shell?

**Comment by freeeco** [comment]
> That's not the same error as the one mentioned in the first command, and that seems like a tidal-listener issue.
> What if you execute tidal-listener from a shell?

Ah yes sorry, looks like there were 2 errors, the one in the atom TidalCycles console pane was the "no environment variable" error and the one in the trace was "Cannot read property 'browseTidal'", the second one seems to be fixed now with the update, but I still get the error in the TidalCycles console pane. I get the same error message when launching tidal-listener from a shell -->

tidal-listener: WITH_GHC: getEnv: does not exist (no environment variable)

**Comment by ndr-brt** [comment]
I think you should open an issue on `tidal-listener` repository
