### ISSUE TITLE
tidal-listener: ngram.js error when booting Tidal

### ISSUE THREAD

**Issue by gamar3is** [tidalcycles/atom-tidalcycles#179]
I'm trying to get the listener going and, after some fighting, I got the Atom plugin to find the tidal-listener interpreter. However, when booting Tidal from the package menu, I get a stack trace:

```
dgram.js:828

Error [ERR_SOCKET_DGRAM_NOT_RUNNING] [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:828:11)
    at Socket.send (dgram.js:606:3)
    at TidalListenerRepl.tidalSendExpression (/home/rlafuente/.atom/packages/tidalcycles/lib/tidal-listener-repl.js:84:14)
    at /home/rlafuente/.atom/packages/tidalcycles/lib/tidal-listener-repl.js:107:14
    at Array.forEach (<anonymous>)
    at TidalListenerRepl._eval (/home/rlafuente/.atom/packages/tidalcycles/lib/tidal-listener-repl.js:97:8)
    at HTMLElement.tidalcyclesEvalMultiLine (/home/rlafuente/.atom/packages/tidalcycles/lib/tidalcycles.js:72:56)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350382)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1230982)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1227116)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284879)
```

and I'm lost here :(

**Comment by gamar3is** [comment]
Ah disregard this -- I got it to work now. I was being thick and running tidal-listener on the console. It's working (with the known limitations) but I'm dying to be able to customise the pattern flashing, which is the feature I really yearned for from feedforward. Thank you for the awesome work here.
