### ISSUE TITLE
Uncaught Error: This Socket is closed

### ISSUE THREAD

**Issue by C1harlieL** [tidalcycles/atom-tidalcycles#34]
Just attempting to install tidal in linux mint but receiving this error when I  boot TidalCycles in Atom. Everything seems to be set up correctly.

`` /bin/sh: ghci: command not found ``

```
events.js:163
Hide Stack Trace
Error: This socket is closed
    at Socket._writeGeneric (net.js:692:19)
    at Socket._write (net.js:743:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Socket.Writable.write (_stream_writable.js:241:11)
    at Socket.write (net.js:670:40)
    at REPL.stdinWrite (/home/loshsmosh/.var/app/io.atom.Atom/data/packages/tidalcycles/lib/repl.js:90:25)
    at REPL.tidalSendLine (/home/loshsmosh/.var/app/io.atom.Atom/data/packages/tidalcycles/lib/repl.js:94:14)
    at REPL.tidalSendExpression (/home/loshsmosh/.var/app/io.atom.Atom/data/packages/tidalcycles/lib/repl.js:99:14)
    at doIt (/home/loshsmosh/.var/app/io.atom.Atom/data/packages/tidalcycles/lib/repl.js:148:18)
    at REPL.evalWithRepl (/home/loshsmosh/.var/app/io.atom.Atom/data/packages/tidalcycles/lib/repl.js:152:9)
    at REPL._eval (/home/loshsmosh/.var/app/io.atom.Atom/data/packages/tidalcycles/lib/repl.js:125:14)
    at HTMLElement.tidalcyclesEvalMultiLine (/home/loshsmosh/.var/app/io.atom.Atom/data/packages/tidalcycles/lib/repl.js:31:55)
    at CommandRegistry.handleCommandEvent (/app/share/atom/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/app/share/atom/resources/app/src/window-event-handler.js:110:40)
```

**Comment by yaxu** [comment]
It's failing to find the `ghci` command (the haskell interpreter). What happens if you do `whereis ghci` from your commandline? Also what happens if you do `whereis stack` ?

**Comment by C1harlieL** [comment]
```
~ $ whereis ghci
ghci: /usr/bin/ghci /usr/share/man/man1/ghci.1.gz
```
```
$ whereis stack
stack:
```

**Comment by yaxu** [comment]
Ok.. In atom menus go to `Edit > Preferences > packages > TidalCycles > Ghci path`.. Make sure that's set to `ghci`. It wouldn't hurt to set it explicitly to `/usr/bin/ghci`

**Comment by yaxu** [comment]
and if you try to run `/usr/bin/ghci` from a terminal window?

**Comment by C1harlieL** [comment]
The ghci haskell interpreter opens as standard
```
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Prelude> 
```

**Comment by yaxu** [comment]
Hmm, then it should work fine. Can you make sure there aren't any spaces in the ghci path setting in atom?

**Comment by C1harlieL** [comment]
Yep, not spaces

**Comment by C1harlieL** [comment]
Could be the same related to this issue:

https://github.com/tidalcycles/atom-tidalcycles/issues/9
install 32 bit haskell instead ??

**Comment by yaxu** [comment]
I don't see how that would help. Your version of ghci seems to be working just fine.. What version of atom are you using?

**Comment by C1harlieL** [comment]
I dunno was just suggested on that thread.

v1.26.0 x64

**Comment by yaxu** [comment]
Ok I've tried installing the same atom version under ubuntu and it works fine. I don't know what's going on here. You could try: deleting what's in the ghci setting (leaving it as the default), upgrading to the latest atom, disabling any other atom packages you have installed (or just wiping your ~/.atom folder if you don't use it for anything else)..

**Comment by C1harlieL** [comment]
ok will try this. Cheers for you help

**Comment by C1harlieL** [comment]
Just reinstalled is now working.
