### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by selcukartut** [tidalcycles/atom-tidalcycles#39]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 0.12.1

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:675

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at REPL.initTidal (/packages/tidalcycles/lib/repl.js:83:27)
    at REPL.start (/packages/tidalcycles/lib/repl.js:110:14)
    at REPL._eval (/packages/tidalcycles/lib/repl.js:120:30)
    at HTMLElement.tidalcyclesEval (/packages/tidalcycles/lib/repl.js:30:44)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:347327)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1227611)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1223745)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:282763)
```

### Commands

```
     -0:05.9.0 tidalcycles:eval (input.hidden-input)
```

### Non-Core Packages

```
tidalcycles 0.12.1 
```

**Comment by yaxu** [comment]
Difficult to know what to suggest here. Were you trying to do something unusual?

**Comment by selcukartut** [comment]
I have installed tidal cycles v1 on a windows machine that has tidal 0.9 before. Later just simple d1 $ sound "bd" and then I got the whole thing. I have deactivated it now and 0.9 version works back again.

**Comment by yaxu** [comment]
My best guess is when configuring the path to BootTidal.hs, you gave the path to the folder and not the full path including the filename. (the atom plugin setting could be a bit clearer about this)

**Comment by selcukartut** [comment]
yes, that seems to be true. now it worked in the way you described.
thanks!
