### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'ghci'

### ISSUE THREAD

**Issue by fabi-ola** [tidalcycles/atom-tidalcycles#48]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.12.6
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 3.0.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'ghci'

```
At fs.js:646

Error: ENOENT: no such file or directory, open 'ghci'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at REPL.initTidal (/packages/tidalcycles/lib/repl.js:137:27)
    at REPL.start (/packages/tidalcycles/lib/repl.js:164:14)
    at HTMLElement.tidalcyclesBoot (/packages/tidalcycles/lib/repl.js:27:26)
    at CommandRegistry.handleCommandEvent (/private/var/folders/t9/4pk04sw91c37nyt15w2vtg3c0000gp/T/AppTranslocation/36BED34F-CB56-422C-9E9D-EB58E652E21D/d/Atom 2.app/Contents/Resources/app/static/<embedded>:11:348418)
    at CommandRegistry.dispatch (/private/var/folders/t9/4pk04sw91c37nyt15w2vtg3c0000gp/T/AppTranslocation/36BED34F-CB56-422C-9E9D-EB58E652E21D/d/Atom 2.app/Contents/Resources/app/static/<embedded>:11:346893)
    at AtomEnvironment.dispatchApplicationMenuCommand (/private/var/folders/t9/4pk04sw91c37nyt15w2vtg3c0000gp/T/AppTranslocation/36BED34F-CB56-422C-9E9D-EB58E652E21D/d/Atom 2.app/Contents/Resources/app/static/<embedded>:1:717210)
    at EventEmitter.t (/private/var/folders/t9/4pk04sw91c37nyt15w2vtg3c0000gp/T/AppTranslocation/36BED34F-CB56-422C-9E9D-EB58E652E21D/d/Atom 2.app/Contents/Resources/app/static/<embedded>:1:725133)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  5x -0:31.9.0 core:backspace (input.hidden-input)
  2x -0:29.3.0 core:save-as (input.hidden-input)
     -0:03.6.0 tidalcycles:boot (input.hidden-input)
```

### Non-Core Packages

```
tidalcycles 3.0.0 
```

**Comment by ndr-brt** [comment]
It seems like you set a wrong path for the BootTidal.hs file.
Can you check this? Did you resolved?

**Comment by fabi-ola** [comment]
@ndr-brt  yes it's resolved! that was the issue :-)
