### ISSUE TITLE
Uncaught Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by niutciut** [tidalcycles/atom-tidalcycles#51]
please help anyone? Just started with this and not sure if I've got everything installed or not.
Put in a tester and this came up

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.1
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 3.1.0

### Stack Trace

Uncaught Cannot call write after a stream was destroyed

```
At events.js:167

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at REPL.stdinWrite (/packages/tidalcycles/lib/repl.js:144:25)
    at REPL.tidalSendLine (/packages/tidalcycles/lib/repl.js:148:14)
    at REPL.tidalSendExpression (/packages/tidalcycles/lib/repl.js:153:14)
    at doIt (/packages/tidalcycles/lib/repl.js:202:18)
    at REPL.evalWithRepl (/packages/tidalcycles/lib/repl.js:206:9)
    at REPL._eval (/packages/tidalcycles/lib/repl.js:179:14)
    at HTMLElement.tidalcyclesEval (/packages/tidalcycles/lib/repl.js:35:44)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -6:23.5.0 core:cut (input.hidden-input)
     -6:21.2.0 tidalcycles:eval (input.hidden-input)
     -6:12.1.0 tidalcycles:eval-multi-line (input.hidden-input)
     -4:52.9.0 core:paste (input.hidden-input)
     -4:42.3.0 tidalcycles:eval (input.hidden-input)
     -4:33.8.0 core:move-left (input.hidden-input)
     -4:32.2.0 core:move-right (input.hidden-input)
     -4:31.3.0 core:backspace (input.hidden-input)
  2x -4:30.2.0 tidalcycles:eval (input.hidden-input)
```

### Non-Core Packages

```
tidalcycles 3.1.0 
```

**Comment by rociogede** [comment]
i have the same problem

**Comment by yaxu** [comment]
Hi, sorry for the delay. My guess is that atom is failing to find haskell. Perhaps it didn't install properly?
Try seeing whether `ghci` runs from the commandline. If it does, paste in `import Sound.Tidal.Context`, to see if the tidal library is installed. If you don't get an error message, that isn't the problem..
A fast way of getting installation support is via this chatroom: https://chat.toplap.org/channel/tidal-install

**Comment by ndr-brt** [comment]
@niutciut did you resolve?

**Comment by ndr-brt** [comment]
closed due inactivity
