### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by jannacek** [tidalcycles/atom-tidalcycles#6]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package, v0.8.5

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:160

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:286:12)
    at REPL.stdinWrite (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:72:25)
    at REPL.tidalSendLine (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:76:14)
    at REPL.tidalSendExpression (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:81:14)
    at doIt (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:130:18)
    at REPL.evalWithRepl (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:134:9)
    at REPL._eval (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:107:14)
    at atom-text-editor.tidalcyclesEval (/Users/Agustin/.atom/packages/tidalcycles/lib/repl.js:29:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -5:48.9.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -5:23.7.0 tidalcycles:eval (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
tidalcycles, v0.8.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by ArcoMul** [comment]
I'm getting this same error, is there a known solution?

**Comment by danielmkarlsson** [comment]
Hi, I've sorted this on my machine by reinstalling brew which in turn reinstalled the commandline tools I had inadvertently borked by reinstalling 10.10.5
Peace be unto you.

**Comment by yaxu** [comment]
Yes my guess is that this error comes from atom not being able to find or execute the 'ghci' program. In that case fixing it is a case of fixing the ghc/tidal install, or going into the atom settings to make sure it has the correct ghci path.

**Comment by humbleai** [comment]
same error. ghci path is correct but ghci console wont show up. is it possible this has something to do with windows 10 creators update?

**Comment by ArcoMul** [comment]
Yes, discussion going on here: https://github.com/tidalcycles/Tidal/issues/200

**Comment by ArcoMul** [comment]
So it seems something is going on in AtomCycles, since running Tidal commands from ghci directly works fine. (See: https://github.com/tidalcycles/Tidal/issues/200#issuecomment-298524643)

When I execute a line in a `.tidal` file it does show the ghci console for me:
![image](https://cloud.githubusercontent.com/assets/1388162/26103195/9d96c762-3a38-11e7-9368-e25d871e5875.png)

With the same warning it has always shown as far as I remember. 

Any ideas on how to continue debugging this?

**Comment by deepbluesome** [comment]
got the same problem. anyone knows the solution?

**Comment by kindohm** [comment]
@jannacek can you update to the latest TidalCycles package in Atom and verify whether the problem has been fixed?

**Comment by jbayardo** [comment]
Hi!. I'm still getting this on Win x64 under stack. Anything I could do?

**Comment by yaxu** [comment]
@jayardo if you're on stack you need to set the ghci path in the atom tidalcycles package settings to `stack ghci`

**Comment by jbayardo** [comment]
@yaxu this is what I get when I boot Tidal after doing that: https://pastebin.com/fRZrD6mJ

I also installed Haskell Platform, and when I try to do it using the default settings, I get: https://pastebin.com/XvMBdi9y

**Comment by yaxu** [comment]
@jbayardo hm, looks like you have an old version of tidal still in stack.. try `stack update; stack install tidal-1.0.7`

**Comment by jbayardo** [comment]
Thanks!, it works now
