### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by Dsm0** [tidalcycles/atom-tidalcycles#79]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 4.2.11
**OS**: "Manjaro Linux"
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 3.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'filter' of undefined

```
At /home/will/.atom/packages/tidalcycles/lib/autocomplete-provider.js:23

TypeError: Cannot read property 'filter' of undefined
    at AutocompleteProvider.getSuggestions (/packages/tidalcycles/lib/autocomplete-provider.js:23:8)
    at providers.forEach.provider (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:287:52)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:258:15)
    at AutocompleteManager.findSuggestions (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:250:17)
    at AutocompleteManager.requestNewSuggestions (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:697:12)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:763:12)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at TextBuffer.emitDidChangeTextEvent (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:2360:24)
    at TextBuffer.transact (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1337:10)
    at TextEditor.transact (/usr/lib/atom/src/text-editor.js:2302:24)
    at mergeIntersectingSelections (/usr/lib/atom/src/text-editor.js:1634:19)
    at TextEditor.mergeSelections (/usr/lib/atom/src/text-editor.js:3885:47)
    at TextEditor.mergeIntersectingSelections (/usr/lib/atom/src/text-editor.js:3850:10)
    at TextEditor.mutateSelectedText (/usr/lib/atom/src/text-editor.js:1633:17)
    at TextEditor.insertText (/usr/lib/atom/src/text-editor.js:1586:25)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/lib/atom/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.didTextInput (/usr/lib/atom/src/text-editor-component.js:1850:24)
```

### Commands

```
     -0:26.8.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:26.1.0 intentions:highlight (input.hidden-input)
     -0:25.9.0 core:save (input.hidden-input)
     -0:25.7.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:22.7.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  4x -0:22.6.0 vim-mode-plus:move-left (input.hidden-input)
     -0:21.8.0 vim-mode-plus:insert-after (input.hidden-input)
     -0:20.6.0 core:backspace (input.hidden-input)
     -0:20.3.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:20 intentions:highlight (input.hidden-input)
     -0:20 core:save (input.hidden-input)
     -0:19.7.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:19.4.0 intentions:highlight (input.hidden-input)
     -0:18.6.0 tidalcycles:eval-multi-line (input.hidden-input)
  2x -0:16.9.0 intentions:highlight (input.hidden-input)
     -0:15.5.0 tidalcycles:hush (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-hydra 0.2.12 
atom-latex 0.8.11 
atom-package-sync 0.4.0 
atom-terminal 0.8.0 
auto-indent 0.5.0 
autocomplete-glsl 0.2.3 
autocomplete-python 1.16.0 
browser-plus 0.0.98 
busy-signal 2.0.1 
foxdot 1.0.0 
glsl-preview 2.0.1 
haskell-hoogle 0.1.3 
Hydrogen 2.12.0 
ide-haskell 2.4.1 
ide-haskell-repl 0.9.0 
ide-r 0.1.8 
improviz 0.5.0 
intentions 1.1.5 
language-glsl 2.0.4 
language-haskell 1.19.1 
language-ipynb 1.3.0 
language-latex 1.2.0 
language-supercollider 0.2.1 
linter 2.3.1 
linter-clojure 1.2.0 
linter-glsl 2.2.0 
linter-python 3.1.2 
linter-ui-default 1.8.0 
min-ui 0.0.4 
monokai 0.24.0 
open_in_cmd 0.6.1 
open-terminal-here 2.3.2 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
project-manager 3.3.8 
supercollider 0.10.0 
tidalcycles 3.8.0 
veda 2.11.4 
vim-mode-plus 1.36.2 
```

**Comment by ndr-brt** [comment]
Found the problem.
In the console you see another error before this exception? Seems like the autocomplete initialization fails. How you configured `ghci path` property?

**Comment by ndr-brt** [comment]
Checkout version 3.8.1

**Comment by ndr-brt** [comment]
It's still an issue?

**Comment by ndr-brt** [comment]
close due to inactivity
