### ISSUE TITLE
Uncaught Error: This socket is closed

### ISSUE THREAD

**Issue by Jabatronic** [tidalcycles/atom-tidalcycles#9]
[Enter steps to reproduce:]

1. Boot TidalCycles
2:
import Sound.Tidal.MIDI.Context
import Sound.Tidal.MIDI.Stream
import Sound.Tidal.MIDI.Synth

devices <- midiDevices

displayOutputDevices >>= putStrLn

m1 <- midiStream devices "LoopBe Internal MIDI" 1 synthController
Error occurs after running the last line

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 0.8.5

### Stack Trace

Uncaught Error: This socket is closed

```
At events.js:160

Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at REPL.stdinWrite (/packages/tidalcycles/lib/repl.js:72:25)
    at REPL.tidalSendLine (/packages/tidalcycles/lib/repl.js:76:14)
    at REPL.tidalSendExpression (/packages/tidalcycles/lib/repl.js:81:14)
    at doIt (/packages/tidalcycles/lib/repl.js:130:18)
    at REPL.evalWithRepl (/packages/tidalcycles/lib/repl.js:134:9)
    at REPL._eval (/packages/tidalcycles/lib/repl.js:107:14)
    at /packages/tidalcycles/lib/repl.js:29:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:42.5.0 tidalcycles:boot (input.hidden-input)
  7x -1:27.7.0 tidalcycles:eval (input.hidden-input)
```

### Non-Core Packages

```
tidalcycles 0.8.5 
```

**Comment by kindohm** [comment]
Do you have the 64-bit version of the Haskell Platform installed? I seem to recall that this issue happens in tidal-midi on Windows with the 64-bit version of the Haskell Platform. By uninstalling the 64-bit Haskell Platform and then installing the 32-bit Haskell Platform, this problem was fixed. As far as I know, this quirk isn't documented anywhere for Windows users of Tidal (yet).

**Comment by kindohm** [comment]
@Jabatronic any update? The Tidal-MIDI package is kind of getting phased out, so maybe we can close this.
