### ISSUE TITLE
stack error update 3.8.7 Windows 10 x64.

### ISSUE THREAD

**Issue by Hoodooman** [tidalcycles/atom-tidalcycles#97]
Hi!
Evrything work perfect with 3.8.1, after update i have stack error. 
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [tidalcycles](https://github.com/tidalcycles/atom-tidalcycles) package 3.8.7

### Stack Trace

Uncaught Cannot call write after a stream was destroyed

```
At events.js:167

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at Ghci.writeLine (/packages/tidalcycles/lib/ghci.js:20:24)
    at REPL.tidalSendLine (/packages/tidalcycles/lib/repl.js:127:17)
    at REPL.tidalSendExpression (/packages/tidalcycles/lib/repl.js:118:14)
    at doIt (/packages/tidalcycles/lib/repl.js:165:18)
    at REPL.evalWithRepl (/packages/tidalcycles/lib/repl.js:169:9)
    at REPL._eval (/packages/tidalcycles/lib/repl.js:142:14)
    at HTMLElement.tidalcyclesEval (/packages/tidalcycles/lib/repl.js:36:44)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1254747)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1250881)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -6:40.2.0 window:run-package-specs (ul.list-inline.tab-bar.inset-panel)
     -6:19.2.0 intentions:highlight (input.hidden-input)
     -6:18.3.0 window:run-package-specs (input.hidden-input)
     -1:13.4.0 core:delete (input.hidden-input)
     -0:38.6.0 tidalcycles:reboot (input.hidden-input)
     -0:11.7.0 tidalcycles:eval (input.hidden-input)
```

### Non-Core Packages

```
atom-nodejs-snippets 2.1.1 
atom-ternjs 0.20.0 
autocomplete-glsl 0.2.3 
browser-plus 0.0.98 
busy-signal 2.0.1 
es6-javascript 1.0.0 
haskell-cleanse 1.0.3 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.13.3 
language-glsl 2.0.4 
language-haskell 1.19.4 
linter 2.3.1 
linter-glsl 2.2.0 
linter-jscs 4.2.4 
linter-jshint 3.1.19 
linter-ui-default 1.8.1 
platformio-ide-terminal undefined 
react 0.18.0 
script 3.25.0 
tidal-autocode 0.6.4 
tidalcycles 3.8.7 
veda 2.13.1 
```

**Comment by Hoodooman** [comment]
extra-prog-path: C:\Program Files\Haskell Platform\8.6.5\msys\usr\bin
extra-lib-dirs: C:\Program Files\Haskell Platform\8.6.5\mingw\lib
extra-include-dirs: C:\Program Files\Haskell Platform\8.6.5\mingw\include
